name: Build docs & deploy to Github pages

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    name: Build docs & deploy to Github pages
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18.x

    - name: Install NPM packages
      run: npm ci

    - name: Build project
      run: npm run build:docs

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist-docs